import type { Metadata } from "next";
import "./globals.css";
import { spaceGrotesk } from "@/lib/font";
import { cn } from "@/lib/utils";
import Navbar from "@/components/elements/Navbar";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import { ReactQueryClientProvider } from "@/components/providers/react-query-provider";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={cn(spaceGrotesk.className, "antialiased relative")}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <ReactQueryClientProvider>
                        <Navbar />
                        {children}
                    </ReactQueryClientProvider>
                </ThemeProvider>
                <Toaster richColors position="top-center" />
            </body>
        </html>
    );
}
