import type { Metadata } from "next";
import "./globals.css";
import { spaceGrotesk } from "@/lib/font";
import { cn } from "@/lib/utils";
import Navbar from "@/components/elements/Navbar";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import { ReactQueryClientProvider } from "@/components/providers/react-query-provider";
import Sidebar from "@/components/elements/Sidebar";
import { SidebarProvider } from "@/context/SidebarContext";
import { SessionProvider } from "@/context/SessionContext";
import { validateRequest } from "@/lib/lucia";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const { user, session } = await validateRequest();
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={cn(spaceGrotesk.className, "antialiased relative")}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <ReactQueryClientProvider>
                        <SessionProvider session={session} user={user}>
                            <SidebarProvider>
                                <Navbar />
                                <Sidebar />
                                {children}
                            </SidebarProvider>
                        </SessionProvider>
                    </ReactQueryClientProvider>
                </ThemeProvider>
                <Toaster richColors position="top-center" />
            </body>
        </html>
    );
}
